menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/xcc3641
    WebLab: /WebLab/
    About: /about/

favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: imxie

# Analytics
# google-analytics:
ga: UA-80145821-1

# Copyright Infomation
startyear: 2014
